"""
Text2SQL AgentOS Playground
============================

Serves the Text2SQL multi-agent workflow via AgentOS.

This exposes the following workflows through the AgentOS UI at http://localhost:7777:
  - IntentRouterWorkflow  – classifies intent, fetches graph context, routes to handler
  - Text2SQLWorkflow      – end-to-end natural language → SQL pipeline

Along with standalone agents:
  - Knowledge Agent       – explores the schema knowledge graph

Usage:
    cd finx-agentic
    uv run python scripts/run_text2sql_playground.py

API endpoints (auto-generated by AgentOS):
    GET  /config                              – AgentOS configuration
    GET  /workflows                           – list all workflows
    POST /workflows/<workflow-id>/runs         – run a workflow
    POST /agents/<agent-id>/runs               – run an agent
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# ── Ensure project root is on sys.path ────────────────────────────────
sys.path.insert(0, str(Path(__file__).parent.parent))

# ── AgentOps observability (must be initialised early) ────────────────
from src.core.agentops_tracker import init_agentops

init_agentops(
    auto_start_session=False,
    tags=["finx-agentic", "text2sql-playground"],
)

# ── Core imports ──────────────────────────────────────────────────────
from agno.agent import Agent
from agno.os import AgentOS

from src.core.model_factory import create_model
from src.knowledge.client import get_graphiti_client
from src.tools.graph_tools import GraphSearchTools
from src.tools.athena_executor import AthenaExecutorTools
from src.prompts.manager import get_prompt_manager
from src.storage.postgres import get_postgres_db
from src.workflows.text2sql import Text2SQLWorkflow
from src.workflows.intent_router import IntentRouterWorkflow

# ── Environment ───────────────────────────────────────────────────────
host = os.getenv("FALKORDB_HOST", "localhost")
port = int(os.getenv("FALKORDB_PORT", "6379"))
database = os.getenv("ATHENA_DATABASE", "non_prod_uat_gold_zone")
athena_output = os.getenv(
    "ATHENA_OUTPUT_LOCATION",
    "s3://aws-athena-query-results-889924997113-ap-southeast-1/",
)
aws_region = os.getenv("AWS_REGION", "ap-southeast-1")
serve_port = int(os.getenv("PLAYGROUND_PORT", "7777"))

# ── Shared dependencies ──────────────────────────────────────────────
client = get_graphiti_client(host=host, port=port)
graph_tools = GraphSearchTools(client=client, default_database=database)
athena_tools = AthenaExecutorTools(
    database=database,
    output_location=athena_output,
    region_name=aws_region,
)
pm = get_prompt_manager()
pg_db = get_postgres_db()

# =====================================================================
# 1. Standalone Knowledge Agent
# =====================================================================
knowledge_instructions = pm.render("knowledge/instructions.jinja2")

knowledge_agent = Agent(
    name="Knowledge Agent",
    model=create_model(),
    user_id="playground",
    instructions=[knowledge_instructions],
    tools=[graph_tools, athena_tools],
    markdown=True,
    add_datetime_to_context=True,
    debug_mode=True,
    db=pg_db,
    enable_user_memories=True,
    enable_session_summaries=True,
    add_history_to_context=True,
    num_history_runs=5,
)

# =====================================================================
# 2. Intent Router Workflow
# =====================================================================
intent_router_workflow = IntentRouterWorkflow(
    id="intent-router",
    graph_tools=graph_tools,
    database=database,
    available_databases=[database],
    db=pg_db,
)

# =====================================================================
# 3. Text2SQL Workflow
# =====================================================================
text2sql_workflow = Text2SQLWorkflow(
    id="text2sql",
    database=database,
    graph_tools=graph_tools,
    max_retries=2,
    track_cost=True,
    db=pg_db,
)

# =====================================================================
# AgentOS – register agents + workflows
# =====================================================================
agent_os = AgentOS(
    description="FinX Text2SQL Playground – multi-agent NL→SQL pipeline",
    agents=[knowledge_agent],
    workflows=[intent_router_workflow, text2sql_workflow],
)
app = agent_os.get_app()

# =====================================================================
# Entrypoint
# =====================================================================
if __name__ == "__main__":
    agent_os.serve(
        app="run_text2sql_playground:app",
        host="0.0.0.0",
        port=serve_port,
    )
