from enum import Enum


class EdgeType(str, Enum):
    HAS_COLUMN = "HAS_COLUMN"
    JOIN = "JOIN"
    ENTITY_MAPPING = "ENTITY_MAPPING"
    QUERY_USES_TABLE = "QUERY_USES_TABLE"
    SYNONYM = "SYNONYM"
    FOREIGN_KEY = "FOREIGN_KEY"
    BELONGS_TO_DOMAIN = "BELONGS_TO_DOMAIN"
    CONTAINS_ENTITY = "CONTAINS_ENTITY"
    HAS_RULE = "HAS_RULE"
    APPLIES_TO = "APPLIES_TO"
    COLUMN_MAPPING = "COLUMN_MAPPING"
    HAS_CODESET = "HAS_CODESET"
    DERIVED_FROM = "DERIVED_FROM"
